sudo: false
language: python
python:
  - 2.6
  - 2.7
  - 3.6
cache:
  pip: true
  ccache: true
  directories:
    - $HOME/deps
install:
  - wget -q $LICENSE_URL -O mod-license >& /dev/null
  - tools/install_deps.sh $HOME/deps $HOME/miniconda $TRAVIS_PYTHON_VERSION `pwd`/mod-license
  - export PATH=$HOME/deps/bin:$PATH
  - source $HOME/miniconda/bin/activate python$TRAVIS_PYTHON_VERSION
  - python -V
script:
  - nosetests --with-coverage --cover-branches
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    secure: "oc/GKd1aITofmBvYBCJ8HGXfSRGHDmUqLeLw8W8bQHQKEU47Hlp/j6CmQujxHTEvkB2XNCGcvxv9dBbOHf7mEtEZ/zNUpHNjec9rms4wDMJVfvGI+xkHOarVKZj6rJrOvHiHoW0URcXpJUZHV98VPw16gLOu5O2uR89h4kWunyJQ8z4cm4LwnkbDbC/zifcy7RkddC2xyPgGs6/9YmYGfECuwRGOlLurveKdXvXDwcwVMb+ClEkv0DiMW8yENixvMnb3MO4aV+vIVbpKY+28F3cFsHbypKxSC1yILyE7V4I7KgzlCtx1TtZyMvNvyZQvFKWuuy5xpiA5pLHE54Jbp8O8FLvjh+H4rxKyeLfnzw9ubDdQw06EYoNTkjerX4IRd/gIaI19Y2a65mJBZNHKVP33byaQ7f3p6swvTysOzB6PGdt5jBG2cFSmQP/o3qNMJS1gnvRcGvOTPi6Ue/WEM5LGmbxLrWzoLK5lCjAlozNMyOeLNgvm3kilIqun37/BzwjwI8c0+P2BcTff54Cq0FjJW8Vcmz475ytFgp8q/Kfy43Q8XPr6gluncq8CeNt4PXrBUi5fzPOoVNOI6U7uDFkW1n5wlsPQh5zSMCgXXpU5/PPgiV4SMLJNZJL4IV06FYByLpdQZUXb0fv/+CluLrFQux6LIJZO31b8eF2Goh4="
